
Proxy:

- name: "u1"
  type: vmess
  server: 143.198.73.143
  port: 443
  uuid: ac611600-7f9d-4bab-b967-a8919ee85b6c
  alterId: 0
  cipher: aes-128-gcm
  udp: true
  tls: true

Proxy Group:

- name: a
  type: select
  proxies:
    - DIRECT
  
Rule:
- DOMAIN-SUFFIX,google.com,a
- DOMAIN-KEYWORD,google,a
- DOMAIN,google.com,a
- DOMAIN-SUFFIX,ad.com,REJECT
- IP-CIDR,127.0.0.0/8,DIRECT
# rename SOURCE-IP-CIDR and would remove after prerelease
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- GEOIP,CN,DIRECT
- DST-PORT,80,DIRECT
- SRC-PORT,7777,DIRECT
# FINAL would remove after prerelease
# you also can use `FINAL,Proxy` or `FINAL,,Proxy` now
- MATCH,a